### ISSUE TITLE
高阶组件代码注入 可以增加以下代码 ✨

### ISSUE THREAD

**Issue by qiguiao** [xdoer/taro-inject-component-loader#5]
/** 如果默认导出的是 高阶  CallExpression */
          if(path.node.declaration.type === "CallExpression"){
            traverse(path.parent, {
              VariableDeclarator(path) {
                if (path.node.init.type === 'ArrowFunctionExpression') {
                  // const A = () => {}
                  // export default A
                  if (path.node.init.body.type == 'BlockStatement') {
                    const mainFnBody = path.node.init.body.body
                    const length = mainFnBody.length
                    const last = mainFnBody[length - 1]
                    insertComponent(last, '' + componentName, state)
                  } else {
                    // const A = () => <div></div>
                    // export default A
                    insertComponent(path.node.init.body, '' + componentName, state)
                  }
                }
              }
            })
          }

**Comment by xdoer** [comment]
你这没考虑高阶里面套高阶
