### ISSUE TITLE
怎么运行demo？

### ISSUE THREAD

**Issue by 132liyh** [xdoer/taro-inject-component-loader#6]
我直接运行你的代码也是没有任何 所谓的组件插入

**Comment by xdoer** [comment]
你运行一下 example?

**Comment by 132liyh** [comment]
就是运行的example

**Comment by xdoer** [comment]
![image](https://user-images.githubusercontent.com/22864183/132614387-8ecf5a9e-f5a6-455a-a05a-a4df383e8289.png)这不是有个大大的 **BaseComponent webpack inject** 吗？看一下页面源代码，和页面展示的效果不就好了？

**Comment by xdoer** [comment]
https://github.com/xdoer/taro-inject-component-loader/blob/3a178ec8137e6bc077e852018e1e32243a41ba08/example/js-taro-react/src/pages/index/index.jsx#L64

**Comment by 132liyh** [comment]
直接运行找不到就不到\taro-inject-component-loader\dist\index.js'

**Comment by xdoer** [comment]
你是直接下载的 example 运行的吗？要把整个项目下载下来，然后先运行 `yarn build`打包一下源码，然后再到 `example/js-taro-react` 运行 demo。

**Comment by xdoer** [comment]
或者你直接在example 里运行 **npm install taro-inject-component-loader** ，然后按照文档，改一下 webpackChain 配置。
![image](https://user-images.githubusercontent.com/22864183/132616404-08933fe4-0b6b-4be8-94b8-1a26bb4c2c2f.png)

**Comment by 132liyh** [comment]
打包可以了，感谢大佬

**Comment by xdoer** [comment]
好的

**Comment by 132liyh** [comment]
还有就是他已经注入成功 但是控制台里面还是提示注入失败

**Comment by xdoer** [comment]
你可以仔细看一下提示的路径，有提示的页面是没注入成功的。对于同一个没注入成功页面，控制台会提示两次，这个目前我还没弄明白为什么。 demo 里关于 connect 的页面，都是没注入成功的。
