### ISSUE TITLE
importPath 能否支持多个组件导入

### ISSUE THREAD

**Issue by thinkingc** [xdoer/taro-inject-component-loader#7]
importPath 支持多个组件导入。

**Comment by xdoer** [comment]
@thinkingc 没啥必要，你直接在这里的 baseComponent 组件里，把多个组件整在一起就好了
![image](https://user-images.githubusercontent.com/22864183/164191781-a2d8d46c-a799-4f9d-9a2a-126d71e1d0b3.png)

**Comment by thinkingc** [comment]
get
